### ISSUE TITLE
Windows 8.1 and .NET 4.5.1

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2402]
In the process of updating to the latest version of SharpDX we ran into the issue of how to support Windows 8.1 moving forward.

Windows 8.1 shipped in October 2013... so its been out for 6 months now.  For Windows 8.1 features you need to build for the .NET 4.5.1 profile.  SharpDX seems to now only support Windows 8.1 and .NET 4.5.1.  The [Steam hardware survey](http://store.steampowered.com/hwsurvey/) shows Windows 8 at 10% and Windows 8.1 at 12%... so still evenly split.

So how we want to deal with this for MonoGame?  Should we support both Win8 and Win8.1 for a while?  Do we just not update to Win8.1 for now?

**Comment by hach-que** [comment]
fyi and not sure this issue is relevant any more, but as of Jan 9th (this commit: https://github.com/mono/MonoGame/commit/189692435f4c7aba06abccca5111440d16e60d09#diff-6042cd1dd58f23b7cb0d594563c07f5fR10) the MonoGame source code is at least using 4.5 features

This kind of caught me off guard since I thought the base framework version was still 4.0 (obv using later frameworks for platforms that require it, but 4.0 for desktop at least).

**Comment by DDReaper** [comment]
I think it's still an issue and thinking on it, I believe the 8.0 game template is no longer valid as it forces you to migrate to 8.1 when you create a new project that being said most new projects target win10 now so it could be left alone.

As to the binaries, possibly we could look to a level of separation with SharpDX and use NuGer / protobuild dep. Using an external package rather than shipping the assemblies ourselves (for those platforms that support it) allowing independent updates from MG.
 thoughts?

**Comment by KonajuGames** [comment]
All platforms we target now support .NET 4.5 at least. I wouldn't feel bad
about dropping Windows 8 and supporting only 8.1, to get back to the now
old original post.

**Comment by hach-que** [comment]
I know @tomspilman is pretty against NuGet / Protobuild packages in general because he doesn't want to introduce external dependencies into MonoGame.

If you do want to add a NuGet reference (likely because the package you're referring to won't be in the Protobuild index), please do it via https://protobuild.readthedocs.org/en/latest/package_management_nuget.html and not `packages.config`, because `packages.config` is not cross-platform aware.

**Comment by hach-que** [comment]
Actually I stand corrected, the Windows Universal platform is using NuGet dependencies (it depends on Microsoft.NETCore.UniversalWindowsPlatform).  This is in the `*.project.json` files inside the MonoGame.Framework folder.

cc @tomspilman

**Comment by tomspilman** [comment]
> Actually I stand corrected, the Windows Universal platform is using NuGet dependencies 

Unfortunately that is required behavior for Win10 support under VS2015... so we have to live with it.

**Comment by hach-que** [comment]
If you wanted to avoid it, you could always put the packages folder (after restoring) into the dependencies repository. This would mean that it doesn't need to restore from the internet because the libraries would already exist in the dependencies folder (like they do for every other platform).

**Comment by tomspilman** [comment]
The world is moving forward to Windows 10...  Windows 8 stuff is legacy and we shouldn't waste time on it any more.
