### ISSUE TITLE
Vertex Texture Fetch Not Supported

### ISSUE THREAD

**Issue by DissidentDan** [mono/MonoGame#2602]
Vertex Texture Fetch is not currently supported by Monogame. It would be great to have support for it. High-priority platforms for me are Windows (DirectX) and PS4.

**Comment by tgjones** [comment]
Just thought I'd mention, because I don't see it in the thread above, that XNA, right back to v1, did have `GraphicsDevice.VertexSamplerStates` and `GraphicsDevice.VertexTextures`. (docs [here](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsdevice.vertextextures.aspx) and [here](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsdevice.vertexsamplerstates.aspx))

However, as per the discussion in #3471, any decision we make on this now probably needs to take Direct3D 12 / Metal into account.

**Comment by tgjones** [comment]
@tomspilman @KonajuGames would you accept a pull request implementing `GraphicsDevice.VertexTextures` and `GraphicsDevice.VertexSamplerStates` (i.e. matching XNA) for Direct3D 11?

I found #2998 - I guess it hasn't been merged because it also includes a number of unrelated changes? Between dabb941 and 2406faa, most of the necessary code seems to be there. Maybe they could be cherry-picked into a new PR. I'm happy to do that.

Since this is just matching an existing XNA API, I'm hoping we can add it now, even if we need to revisit the broader `GraphicsDevice` API again in the future, when we look at Metal / Direct3D 12 / Vulkan.

(As a motivating example: several terrain algorithms - geoclipmapping, CDLOD, even sometimes geomipmapping - rely on sampling a heightmap in the vertex shader. That's what I'd like to use it for. It's something I previously had working in XNA.)

**Comment by DissidentDan** [comment]
Let me know if there's anything I can do to help.

**Comment by tgjones** [comment]
Cool, thanks @DissidentDan. Let's see what @tomspilman and @KonajuGames think.

**Comment by tgjones** [comment]
I think I'm going to go ahead and implement this, because it's holding me up, and I'll optimistically hope that it will be accepted. Obviously I'll be happy to change it after discussion.

**Comment by KonajuGames** [comment]
Sure @tgjones .  Sorry for the delay in responding.  Lots of other things happening, and unfortunately some threads get missed in the process.

**Comment by tomspilman** [comment]
> would you accept a pull request implementing  GraphicsDevice.VertexTextures  and  GraphicsDevice.VertexSamplerStates  (i.e. matching XNA) for Direct3D 11?

Sure....  I totally didn't realize XNA already had that feature in this way.

Still doesn't change the questions about OpenGL support, but it can be stubbed out for now.

> I found #2998 - I guess it hasn't been merged because it also includes a number of unrelated changes?

Yes... that is exactly why that didn't get quickly merged.  Cherry picking from it would be a good place to start.


> when we look at Metal / Direct3D 12 / Vulkan.

Yeah... no worries about that for now.

**Comment by tgjones** [comment]
Great, thanks @KonajuGames and @tomspilman. I'll hopefully submit a PR later today.

I'll stub out OpenGL support for now. I am interested in getting it working on OpenGL, but that can be done separately.

**Comment by DissidentDan** [comment]
The biggest roadblock with OpenGL is that the version of MojoShader (the tool that converts the MS Effect framework shaders into OpenGL shaders) is pretty old and doesn't support texture sampling in vertex shaders.

**Comment by tomspilman** [comment]
> MojoShader (the tool that converts the MS Effect framework shaders into OpenGL shaders) is pretty old and doesn't support texture sampling in vertex shaders.

That will just have to wait for our removal of MojoShader then.

**Comment by flibitijibibo** [comment]
Some work regarding vertex textures in OpenGL (because MojoShader or not it's going to be really fun for the author):

The way vertex textures are done in XNA4 is that is basically just takes the last 4 sampler slots available for the D3D9 graphics device, and calls those "vertex" textures. Those samplers then get sent to the vertex shader's sampler registers with modified indices (so if you use register 0 in the shader, the new register is now maxSamplers - 4 + 0).

Whoever implements this will need to both send the vs_s? samplers those new uniform values as well as ensure that VertexTexture/VertexSamplerState applications will apply to the right texture image unit. The relevant work for this in FNA can be nabbed from here:

https://github.com/flibitijibibo/FNA/commit/2f52bd863b60a3aa921092b112f4a89c1b98bff5
https://github.com/flibitijibibo/FNA/commit/15a9c7bbce618f71f0453378d4240a8fc68e61bb

The FNA Effect now depends on MojoShader even at runtime, so the shader-specific changes are found here:

https://github.com/flibitijibibo/MojoShader/compare/eca4c73...af2d6e1

Also note that vertex sampler state changes also need to be applied in the right place, so you'll need to check which shaders the samplers are used in, and it might be both vertex and pixel!

Other MojoShader work related to vertex texture/sampler parsing can be found in the gigantic MojoShader-FNA patch (though the good news is you only care about the diffs in mojoshader.c, the rest is either Effect support or FNA-specific changes like glProgramViewportFlip):

http://flibitijibibo.com/mojoshader-fna.patch

It's a lot of junk, but the result is there! Using the vertex texture visual test code:

http://www.flibitijibibo.com/images/vtexgl.png
