### ISSUE TITLE
GameComponents added during Initialize() never have Initialize() or LoadContent() called

### ISSUE THREAD

**Issue by RayBatts** [mono/MonoGame#2943]
This one's a little bit tricky.

InitializeExistingComponents() is called during Game.Initialize, which takes a copy of all of the currently registered components and calls Initialize on them. If ComponentA is initialized like this and within that Initialize() call creates and adds ComponentB, ComponentB will never have the chance to initialize itself. The timing is a bit specific, as pretty much any GameComponents added during Game.Initialize() won't have the proper chance to initialize itself.

During InitializeExistingComponents(), we need to be checking the collection for changes and calling Initialize() on any new components added during this step.

**Comment by InfiniteProductions** [comment]
I come across this issue recently with a recent MG dev build and in order to make things simple, I have created a test solution on both MG and XNA 4 (both Windows DX platform)

MG output:

> DC1 contructor
DC1 intialize
DC2 constructor
DC1 add component DCTwo
DC1 call base.Initialize
DC1 LoadContent
DC1 Update
DC1 Draw
DC1 Update
...

XNA output:

> DC1 contructor
> DC1 intialize
> DC2 constructor
> DC1 add component DCTwo
> DC1 call base.Initialize
> DC1 LoadContent
> DC2 LoadContent
> DC1 Update
> DC1 Update
> DC1 Draw
> DC1 Update
> DC1 Draw
> ...

as you can see XNA makes LoadContent from DC2 called whereas MG didn't ! Unfortunately without more intel regarding this I can't say it's an issue or a design choice (which could be bad). The fact is XNA does something MG doesn't do, which may cause issues (the one I got comes from Catalin Zima deferred lighting code converted to XNA 4.0 by Roy Triesscheijn). The test solution is designed almost the same way, except the scene class.

The workaround I made is a public method which call the protected LoadContent method from DC2 when called explicitly (not super good, but it's working at least).

Files:
[MGIssue2943.zip](https://github.com/mono/MonoGame/files/372066/MGIssue2943.zip)

**Comment by tomspilman** [comment]
Thanks @InfiniteProductions .

It should be easy to setup a unit test based on your findings and make the correct fix to match XNA behavior.

**Comment by InfiniteProductions** [comment]
There is a related question on [stackoverflow](http://stackoverflow.com/questions/742651/loadcontent-does-not-work-in-my-components) which may help.

**Comment by nkast** [comment]
@RayBatts, @InfiniteProductions 
Please test #5020 http://teamcity.monogame.net/viewLog.html?buildId=19039&buildTypeId=MonoGame_TestWindows&tab=artifacts#!
