### ISSUE TITLE
2MGFX is hard coded to 64 bits.

### ISSUE THREAD

**Issue by scratch2procd** [mono/MonoGame#3365]
Running on 32 bit WIndows 7 got;
2MGFX.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the pro
gram, and then contact the software publisher.

Looking at the code it seems MojoShader.cs is hardcoded with
const string mojoshader_dll = "libmojoshader_64.dll";

I can build a 32 bit version by adding libmojoshader_32.dll to the project and changing the hardcoded line above and then changing the build target to "Any CPU"

Would need to check the sizeof a UINT to determine which dll to load at runtime and probably update protobuild files to update the project details for a proper solution.

**Comment by tomspilman** [comment]
Hey @scratch2procd.

It is working right now as we intended and there are no plans to change it.

We used to support only 32bit with the 2MGFX and MGCB tools.  The problem with that, in particular with MGCB, is that modern game content has gotten really big.  

For example we have a terrain processor where we frequently run out of memory under XNA.  We spent significant time reworking the processing steps, breaking tasks down into smaller bits, etc.... and still we have cases where we have no choice but to tell the artists to give us lower resolution source art.

This was entirely a waste of our time.  My machine has 16GB in it, yet because XNA is 32bit only...  I was stuck only able to process less than 3GB of content at a time.

Around then is when we put some serious effort into adding 64bit support into the new pipeline for MonoGame.  We did the same tricks to access native code... we have to build and maintain 2 dlls...  package both dlls with each tool...   take a guess at runtime which one to use.  This had two complications.

First it was a complete mess to maintain.  Building, updating, packaging, loading, and debugging 2 different native dlls for the 5 or 6 different native code libraries we depended on was error prone and tiresome.  Especially when it was hard to get 64bit versions of some of these libraries... we had to manually build a lot of these ourselves (sometimes with custom patches)... then redo that work twice when any one needed to be updated.

Second it made the custom processors sometimes not work.  If the custom processor you happened to build was set to only run 32bit...  as long as you happened to only run on 32bit machines this was no problem.  If you then one day happened to build your content on a 64bit system... like the build server... the processor mysteriously stopped working.  I say mysteriously because it wouldn't kick out a nice "this dll is 32bit and it must be 64bit" error...  it would say "invalid image format" or something cryptic like that which could mean any one of a dozen different problems.

We then looked at the hardware out there.  64bit processors and OSs have been mainstream for at least 10 years now.  Looking at the Steam hardware survey over 85% of gamers had 64bit machines...  I would expect that number to be even higher if we surveyed game developers.  Heck even iPhone is going 64bit only.

To us the extra work to maintain both 32bit and 64bit... considering game content is getting bigger every day and 64bit is a vastly more popular OS choice... seemed dumb.  MonoGame is run by a very small team that only really work on it in their spare time.  We have to focus on the right things... and maintaining 32bit support wasn't one of them.

That said... unlike XNA... MonoGame is open source.  You are free to make a patch that makes the 2MGFX and MGCB tools support 32bit platforms again.  We just won't be wasting any efforts on supporting it in the official repo anymore.

**Comment by scratch2procd** [comment]
Thanks for the clarification. Just struck me as odd that everything else worked in 32 bit mode except for that. I may be wrong but I think my suggestion of loading the dll dependant upon UINT size would enable an executable that would run in 32 or 64 bit mode. I'll have a look when I get some time.

**Comment by tomspilman** [comment]
> I may be wrong but I think my suggestion of loading the dll dependant upon UINT size would enable an executable that would run in 32 or 64 bit mode.

You are basically right, but making it load the right DLL wasn't what hurt us...  it was all the maintenance involved in supporting 2 paths.

**Comment by tomspilman** [comment]
You can see in these two PRs...

 https://github.com/mono/MonoGame/pull/2430
 https://github.com/mono/MonoGame/pull/2438

... how the 32bit support was removed.

**Comment by Bambofy** [comment]
I would like to build a 32 bit version of monogame and all the extras, would this be difficult? I can't use the pipeline tool because i'm running 32bit OS.

**Comment by tomspilman** [comment]
@Bambofy  - The PR links above should help, but we have no plans to support 32bit desktops moving forward.
