### ISSUE TITLE
[iOS] Disable "Generate overflow checks"

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#3438]
After upgrading to the unified API we started getting overflow exceptions in MonoGame here:
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentReaders/Texture2DReader.cs#L195

Here ushort is cast to byte. Disabling "Generate overflow checks" resolves the issue.

We need to stop adding `<CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>` to the debug build configurations.
@hach-que Can you remove it?
https://github.com/hach-que/Protobuild/blob/fea0c15222535b3dac5a536f3d8dbd04bc5d6179/Protobuild.Internal/BuildResources/GenerateProject.CSharp.xslt#L496

`<AllowUnsafeBlocks>True</AllowUnsafeBlocks>` can be removed too because the default value is true and it is a project level toggle, not a configuration level one.

![proj](https://cloud.githubusercontent.com/assets/431167/5821349/aa48dd14-a0cb-11e4-87e6-5a031cbf2cbe.png)

**Comment by tomspilman** [comment]
Is a better fix here to add `unchecked` block around these particular cases where overflow is expected?

**Comment by hach-que** [comment]
These options have actually always had this setting according to the Git history, so it's a bit weird they only started causing issues in the Unified API.

Anyway, only iOS seemed to have this on by default, and only in Debug mode.  Since that makes it inconsistent across platforms, I've moved this to a CheckForOverflowUnderflow property to enable the checked arithmetic functionality, which by default is off.

I've also removed the additional `<AllowUnsafeBlocks>True</AllowUnsafeBlocks>` option in the configuration mapping because it's redundant (it's always on for Protobuild projects).

**Comment by hach-que** [comment]
The Protobuild executable on the master branch of the Protobuild repository now has the changes described above: https://github.com/hach-que/Protobuild/blob/master/Protobuild.exe

**Comment by hach-que** [comment]
The documentation for this new property can be found at http://protobuild.readthedocs.org/en/latest/project_properties.html#checkforoverflowunderflow.

**Comment by Nezz** [comment]
@tomspilman .NET has no overflow checks by default. This seems to be a Xamarin thing.
@hach-que Thanks! Overflow check wasn't working with the previous API for some reason.

**Comment by Nezz** [comment]
How can we make progress with this?

**Comment by hach-que** [comment]
Protobuild needs to be updated in the MonoGame repository.

**Comment by Nezz** [comment]
I have submitted a PR.
