### ISSUE TITLE
Cannot clone some required git submodules

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3464]
Hey all,

When cloning the repo today for use on my Win8 machine, I found that after running `git submodule init`, `git submodule sync`, and `git submodule update`, I can clone down the submodule in `ThirdParty/Kickstart`, but not the one in `ThirdParty/Libs`. I can confirm that the user @kungfubanana no longer exists (note that his name is no longer bolded when referenced), and therefore the dependencies that were contained in one of his repos no longer exist in one place. I am pretty sure that this has happened in the past few days, because he was referenced in https://github.com/mono/MonoGame/issues/3430 only three days ago. Maybe we can contact GitHub and ask them for a copy of the repo? I'm sure that they have backups going back weeks if not months, which should be plenty far enough.

![capture](https://cloud.githubusercontent.com/assets/4739008/5893538/59d7b424-a4b6-11e4-84c4-29eb1c29ddd2.PNG)

**Comment by WardBenjamin** [comment]
Any ideas @tomspilman?

**Comment by tomspilman** [comment]
> note that his name is no longer bolded when referenced

 I guess someone deleted his account on GitHub.  That basically broke all old master branch references.

 Try manually updating the dependencies reference to...

https://github.com/Mono-Game/MonoGame.Dependencies/commit/629b0482d1a01cd365c429cd0221d7bb6a94e01d

 ... that should be the same state as the old repo.

Git is bad at changing a submodule reference to point to another repo.  So fixing it may be challenging.

**Comment by WardBenjamin** [comment]
Alright, will do. I'll report back if I can figure this out. If not, I can always just branch the dependencies repo from that point and host it myself.

**Comment by WardBenjamin** [comment]
So, time for the report. I could not get the git submodule to accept a specific commit to pull from, however I have relocated a copy of the repo to [WardBenjamin/MonoGame.Dependencies](https://github.com/WardBenjamin/MonoGame.Dependencies). I am going to submit a pull request with a simple fix for the .gitmodules file referencing this.

**Comment by tomspilman** [comment]
> I could not get the git submodule to accept a specific commit to pull from

How is it that it doesn't work for...

 https://github.com/Mono-Game/MonoGame.Dependencies

... but it works for your repo?

They are both referencing a revision on a different repo.  This should work with our repo.


> I am going to submit a pull request with a simple fix for the .gitmodules file referencing this.

Don't do that... we won't merge it.

We cannot go from depending on someone's personal repo to someone else's personal repo.

**Comment by WardBenjamin** [comment]
> They are both referencing a revision on a different repo. This should work with our repo.

Alright, that isn't a problem. I didn't know if the official repository would actually work in this instance, now that the repo is inconsistent with the original repo that was being used. May I ask why this hasn't been previously addressed?

**Comment by tomspilman** [comment]
>  now that the repo is inconsistent with the original repo that was being used

You are missing my point.

All submodules reference a particular revision within a repo.

When i created the new official dependencies repo I specifically made a copy of the old repo at revision `7944be7`.  Note how in the master branch Libs folder we are referencing that same revision...

  https://github.com/mono/MonoGame/tree/master/ThirdParty

This means the first commit into the new dependencies repo is binary identical to the revision that the 3.2 release of MonoGame was using.

As long as the repo url is updated and the revision is changed to `629b0482d1a01cd365c429cd0221d7bb6a94e01d` things should work.

Fixing existing clones of the MonoGame master repo is a pain.  Some might need to make a new clone to fix their local copies or get into manual editing/deleting of files.

> May I ask why this hasn't been previously addressed?

Because we didn't want to deal with the fallout of changing the submodule reference.

**Comment by WardBenjamin** [comment]
Alright, thanks for the clarification.
