### ISSUE TITLE
Implement Render Metrics.

### ISSUE THREAD

**Issue by Shqrdx** [mono/MonoGame#3624]
This is a topic about implementing metrics system for MonoGame. Metrics should calculate GPU draw calls and other stuff. It must be simple and effecient in term of performance.
Here is a few points :

-The @KonajuGames suggest static class Metrics which could calculate GPU rendering calls and helps  developer to optimize his projects.
-My suggestion is Metrics for SpriteBatch which could calculate draw calls.

Discuss.

**Comment by tomspilman** [comment]
So I agree with @KonajuGames that we need some `Metrics` type.

First it shouldn't be static.... we should avoid any statics moving forward just because we want to support more threading later.  It should probably be accessible from `GraphicsDevice`.

Also I think it needs to be a struct type to allow for easy copy of the metrics.  This leads into making it easy to store/restore/clear metric states.  For example you want to track separately the cost of rendering in your shadow passes... store the metrics before, grab the metrics after, and subtract them.

By default the metrics shouldn't do anything but count up.  We could maybe have them reset automatically before `Game.Draw` is called, but that is all we should do.

Most of what we should count should be primary performance considerations like:

  - `NumDraws`.
  - `NumClears`
  - `NumTargets`.
  - `NumTextures`.

We could maybe add more details, but we need to remember this is for quick troubleshooting and not a replacement for GPU debugging/profiler tools.  

If we want to single out `SpriteBatch` for extra care we could store `NumSprites` and/or `NumStrings`.  `SpriteBatch` would just internally increment these on the `Metrics` object in the `GraphicsDevice`.

**Comment by Zoldike** [comment]
It would be great to get the batch count between SpriteBatch.Start and SpriteBatch.End. That would be really useful to detect often texture changes.

**Comment by KonajuGames** [comment]
> It would be great to get the batch count between SpriteBatch.Start and SpriteBatch.End. That would be really useful to detect frequent texture changes.

Could be useful, but not accurate to determine texture changes.  A batch will also be sent to the GPU when the internal buffer is filled.

**Comment by Zoldike** [comment]
>Could be useful, but not accurate to determine texture changes. A batch will also be sent to the GPU when the internal buffer is filled.

I thought these metrics should be more general than the exact number of texture changes.

**Comment by tomspilman** [comment]
> It would be great to get the batch count between SpriteBatch.Start and SpriteBatch.End.

In what I propose you would do something like:
```
var start = graphicsDevice.Metrics;
spriteBatch.Begin();
// Do drawing
spriteBatch.End();
var metrics = graphicsDevice.Metrics - start;
var batchCount = metrics.NumDraws;
```

**Comment by tomspilman** [comment]
> I thought these metrics should be more generic than 
> the exact number of texture changes.

The metrics should consist of useful info about what commands we're sending to the GPU.

Texture changes being how many times did we change textures on the GPU.  This is potentially different than how many times you call `GraphicsDevice.Textures[0] = tex`.

**Comment by tomspilman** [comment]
So with https://github.com/mono/MonoGame/pull/3803 merged is this issue ready to be closed?

**Comment by Shqrdx** [comment]
Yes it is.
