### ISSUE TITLE
Replace sdl mixer 1.2/openal with...

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3625]
So Linux uses sdl1.2 mixer which is deprecated and it should be replaced... 
WindoiwsGL uses OpenAL that loads an entire song instead of just buffering it...
So what would be a good replacement that is cross platform(Windows / Linux / Mac)?

**Comment by tomspilman** [comment]
Not sure.

Ideally we would have a solution in an existing library like OpenTK or have access to some platform specific APIs (like maybe use WMS on Windows).

The other idea would be to write our own decode and stream solution in pure C#.

**Comment by KonajuGames** [comment]
There is [NVorbis](http://nvorbis.codeplex.com/), a pure managed Ogg decoder, as used by Renaud Bedard in his [OggStream](http://theinstructionlimit.com/ogg-streaming-using-opentk-and-nvorbis) class.

**Comment by flibitijibibo** [comment]
I eventually moved to a DynamicSoundEffectInstance, streaming with direct Vorbisfile functions:

https://github.com/flibitijibibo/FNA/blob/master/src/Media/Xiph/Song.cs
https://github.com/flibitijibibo/Vorbisfile-CS

The thread's there since we don't update instances on an audio thread, but it's technically optional. The one bug with the non-threaded mode is that MediaPlayer.OnSongFinishedPlaying is not called, since any place I put it caused lots of fun with infinite loops.

Like with the PackedVector stuff you can redo any license headers as needed, and switch out libraries for something like NVorbis if Vorbisfile# isn't preferred.

**Comment by tomspilman** [comment]
> eventually moved to a DynamicSoundEffectInstance, streaming with direct Vorbisfile functions

That is actually what I was about to suggest.

For the target platforms... Windows, Mac, Linux... we have plenty of CPU threads to throw at decoding and streaming audio.  And the work isn't very heavy in the first place.

This will force us to fix/implement `DynamicSoundEffectInstance` which we've not done so far.

I think this is a good plan.

**Comment by cra0zy** [comment]
So I thought all were ok with using Vorbis-CS since no one had any objections about it... I was wrong.

Anyway let's do a poll, and type in what you think is better:
1) NVobris
2) Vobris-CS

I vote 1.

**Comment by KonajuGames** [comment]
As noted above, I would prefer a managed solution such as NVorbis.

**Comment by tomspilman** [comment]
> 1) NVobris

 Pros:
   - No extra libraries to manage.
   - Works on any platform we need it.
   - Already used in games like FEZ.

 Cons:
   - Might lack some features (seeking was mentioned).
   - Might have compatibility issues with some ogg files.
   - Likely decodes slower than native solution.


> 2) Vobris-CS

You mean Vorbisfile-CS which was linked above.

Pros:
   - Probably the best performance.
   - Most features.
   - Most correct.

Cons:
  - We need to manage at least two more library dependencies per-platform... more if we ever have to deal with x86 vs ARM vs x64.
  - Would need to port/build for any additional platforms we want to target.

**Comment by cra0zy** [comment]
@tomspilman What do you vote, 1 or 2, which do you think is better?

**Comment by tomspilman** [comment]
Don't know for sure.  Maintainability is my biggest concern and NVobris is vastly easier to maintain.  However I worry what the performance difference is with native decoding and *if* that matters in the end.

**Comment by tomspilman** [comment]
This discussion is interesting:

http://nvorbis.codeplex.com/discussions/578755

 On performance:

 > Audacity seems to be able to decode a 3 minute song in about 1/2 seconds, decoding the same .ogg song with NVorbs however takes much longer 4/5 seconds+.

 On libvorbisfile:

> libvorbisfile is a file-based decoder and does all the decoding up front. NVorbis is a stream-based decoder and decodes as requested.

**Comment by tomspilman** [comment]
Also note Rrenaud's fork of NVorbis on github:

 https://github.com/renaudbedard/nvorbis

Don't know the differences/changes specifically to the official release.

**Comment by KonajuGames** [comment]
File-based decoding is a big negative.  So much so that I would consider it
out of the running.​

**Comment by KonajuGames** [comment]
Also consider that the 1/2 seconds to decode a 3 minute song is to decode the entire file in one blast.  The extra few seconds that NVorbis takes to decode would be amortised across the entire duration of the song.

**Comment by tomspilman** [comment]
> File-based decoding is a big negative.

But is that accurate?  Seems to defeat the purpose of streaming if that was the case.

**Comment by KonajuGames** [comment]
Looking at some [libvorbis examples](http://bluishcoder.co.nz/2009/06/26/decoding-vorbis-files-with-libvorbis.html), it would appear that streaming is supported.  Not sure what they meant by file-based decoding and decoding up front then.

**Comment by cra0zy** [comment]
So, should I start adding Nvorbis?

**Comment by flibitijibibo** [comment]
I'd actually vote NVorbis as well depending on how many targets this ends up supporting. For Vorbisfile# we actually do something really silly due to how managed memory gets moved around at runtime:

https://github.com/flibitijibibo/Vorbisfile-CS/blob/master/Vorbisfile.cs#L103

So the maintenance/performance costs are probably worth not having to check `sizeof(Ogg_Vorbisfile)` with every platform's C compiler (if they even provide one, tsk tsk) to get it working everywhere.

I think some of Renaud's NVorbis work eventually got merged, but a lot of it is cruft from when he was writing the OggStream, which is still kind of a mess...

https://github.com/flibitijibibo/FNA/blob/fez-sdl2/MonoGame.Framework/SDL2/Audio/OggStream.cs

... so I wouldn't worry about that too much.

Probably one thing to extend the DynamicSoundEffectInstance with for NVorbis is something like `SubmitFloatBufferEXT`, where you can send float values directly rather than having to convert the whole array to uint16 values. OpenAL has AL_ext_float32 to deal with those samples, not sure about the other backends though.

**Comment by tomspilman** [comment]
Ok... lets go with Nvorbis then.

**Comment by cra0zy** [comment]
Implemented with #3832
