### ISSUE TITLE
BasicEffect leaks memory after Dispose() call

### ISSUE THREAD

**Issue by ala53** [mono/MonoGame#3635]
If you create a lot of BasicEffects (1 at a time or in bulk) and then dispose them, there is pretty big memory leak. I've tried forcing GC.Collect() but it doesn't help. Somewhere, unmanaged memory is allocated but never released when you create BasicEffects.

A simple demo is here - it allocates and then destroys 100 BasicEffects per frame, then calls a full GC. On Windows DirectX, it leaks 5-10 mb per second.
https://gist.github.com/ala53/5aff5801b66fe4c55548

(This is on MonoGame 3.2)

**Comment by tomspilman** [comment]
> it allocates and then destroys 100 textures per frame

How is that equal a `BasicEffect` leak?

**Comment by tomspilman** [comment]
> This is on MonoGame 3.2

You need to test with MonoGame 3.3... it is completely possible this is already fixed.

**Comment by ala53** [comment]
@tomspilman Sorry, typo. 

Just tested with MonoGame 3.3 and the same behavior exists. Memory use jumps regardless of GC's.

**Comment by Shqrdx** [comment]
This issue is fixed on WinDX, I tested it.. here is result of memory profiling without Dispose call

![image](https://cloud.githubusercontent.com/assets/3036176/9324919/3b4a7424-4597-11e5-9514-568102b8620e.png)

and here is the result with Dispose call

![image](https://cloud.githubusercontent.com/assets/3036176/9324938/604e54c0-4597-11e5-8c47-3ed7e1d0f6d5.png)

I also tested it with task manager and found same results too..
