### ISSUE TITLE
[Pipeline,WIN] Compress=true crashes on small files (sample inside)

### ISSUE THREAD

**Issue by Eversor** [mono/MonoGame#3664]
As in the following sample, a small wav file will crash the entire compile tree if Compress is set to TRUE

https://www.dropbox.com/s/lo9c33iuj8m9pet/CrashTest_Compress_SmallFile.zip?dl=0

**Comment by tomspilman** [comment]
@KonajuGames - Didn't you add the compression feature to the pipeline?  Any ideas?

**Comment by KonajuGames** [comment]
I'm looking into it now.  It would appear that it is possible for LZ4 compression to fail given certain input streams.  This is a trade-off to get compression speed.  I'm currently trying to work out how to best detect the compression failure and write that XNB without compression.

**Comment by KonajuGames** [comment]
Added PR #3737 to fix this by writing the file uncompressed if the content compression fails for any reason.  I want to add a test suite since you have helpfully provided a small test file that exhibits the problem. @Eversor is it ok for us to include exp.wav in our test suite since it exhibits the issue?

**Comment by Eversor** [comment]
Yes of Course, feel free to add it!

**Comment by KonajuGames** [comment]
Thanks @Eversor
