### ISSUE TITLE
xamarin template addin not generated successfully

### ISSUE THREAD

**Issue by shelbyladallen** [mono/MonoGame#3764]
maybe I misunderstand, but wasn't the development branch supposed to add template support for monodevelop/xamarin? I'm trying to build the addin using the project, it claims to succeed, but xamarin can't find any addins to install.

**Comment by tomspilman** [comment]
@shelbyladallen - We actually just put the download link up for the development version of the MonoGame installer for Mac...

 http://www.monogame.net/downloads/

Maybe you should give that a try?

**Comment by dellis1972** [comment]
The Project does not produce the .mpack that you need to install the addin into Xamarin Studio. You have to run a bunch of mdtool commands to get that to work. Check the default.build script in 

IDE/MonoDevelop

You will see some calls to mdtool setup etc. Alternatively just run nant in the IDE/MonoDevelop directory and it will generate it. 

That said, I just published a new version in the Beta channel in the addin so that should come though very soon (once its published)

**Comment by shelbyladallen** [comment]
first off it's amazing you both responded so quickly.

I'm trying both solutions and will report back.

**Comment by shelbyladallen** [comment]
Ok the binary worked like a charm! the templates are there. I tested the
monomac one and it worked immediately.

I also tried the opengl one and got "File 'OpenTK.dll.config' already
exists in project. Do you want to overwrite it?". Just fyi

I tried the other method but was having trouble finding/installing nant,
i'm a little short on sleep so that's probably my bad.

Thanks again!

**Comment by tomspilman** [comment]
> I also tried the opengl one and got "File 'OpenTK.dll.config' already
exists in project. Do you want to overwrite it?". Just fyi

Interesting... @dellis1972 ?

**Comment by cra0zy** [comment]
> I tried the other method but was having trouble finding/installing nant,
> i'm a little short on sleep so that's probably my bad.

The reason it occurs is because you can't set files from nuget packages to copy if newer, so the config file had to be included in both nuget package and project template.

**Comment by dellis1972** [comment]
what @cra0zy said :) Closing this issue as it worked :D
