### ISSUE TITLE
Problems with new effect preprocessor

### ISSUE THREAD

**Issue by mgarstenauer** [mono/MonoGame#3853]
I have encountered several problems compiling DirectX Effects. I assume that they are caused by the new preprocessor (https://github.com/mono/MonoGame/issues/1972). Before everything worked fine.

Here are two effects for reproducing the problems:

Effect.fx
```
float4 VS(float4 pos : SV_Position) : SV_Position
{
  return pos;
}

float4 PS() : COLOR
{
  return float4(0, 0, 0, 0);
}

technique
{
  pass
  {
    VertexShader = compile vs_4_0 VS();
    PixelShader = compile ps_4_0 PS();
  }
}
```

Effect2.fx
```
#define DEF0 0
#define DEF1 0
#define DEF2 0
#include "Effect.fx"
```

Effect.fx compiles without a problem. But the following problems appear when compiling Effect2.fx:

**Problem 1:** When Effect.fx does not end with a newline (CRLF) the following error is output:
`Effect.fx(18,2): error X3000: syntax error: unexpected token '#'` 

**Problem 2:** When Effect.fx ends with a newline (CRLF) the following error is output:
`Effect.fx(19,7): error X1500: syntax error : unexpected token '-'`

When I remove one of the #define in Effect2.fx or when I change one of the lines from `#define DEF0 0` to `#define DEF0 1`, it compiles without a problem. Note that these #define don't do anything. So this seems to be a problem purely of the preprocessor.

**Problem 3:** When compiling complex effects with many include files, the line numbers at which errrors are reported are off.

**Comment by tgjones** [comment]
* I'm working on a fix for **Problem 1**.
* I haven't seen **Problem 2** - can you post a minimal failing test file(s)?
* I have seen **Problem 3** - I know that multiline comments cause incorrect line numbers in error messages. I'm not sure if that's the only issue, but it's certainly an issue.

**Comment by mgarstenauer** [comment]
Thanks for the response. [Here](http://1drv.ms/1ELSw5q) is my test case. Let me know if you need something else.

(Note: None of this is time critical. I have managed to work around these issues so far. But in the long term it should probably be fixed.)

**Comment by tomspilman** [comment]
Thanks for reporting this @mgarstenauer !  We felt we would get some tricky issues from the switch in preprocessors... so just working thru these bugs as we trip up on them and improving our unit tests.

**Comment by tomspilman** [comment]
@tgjones - Did you finish that fix?

Also for "Problem 3" we *need* to find a fix for that ASAP.  If there is something i hate the most it is getting bad line numbers in error messages.

**Comment by tgjones** [comment]
@tomspilman I'm starting to get a little more time, so I hope to look at this in the next few days. Apparently newborn babies reduce one's available time for playing with 3D things, who'd have thought :)

**Comment by KonajuGames** [comment]
> Apparently newborn babies reduce one's available time for playing with 3D things, who'd have thought :)

They do that well.  And believe me, it continues for many years yet.

**Comment by tgjones** [comment]
I've been looking at **Problem 3**. The bad news is that CppNet seems quite flawed in its handling of line numbers. My simple tests with `include`s reveal that when CppNet's lexer returns from an included file to the parent file, the line number it continues from is off by one. And the line numbers in included files are wrong too.

I've been able to slightly improve things in MonoGame, by feeding CppNet with strings that have had `\r\n` replaced with `\n`, and reporting errors for included files using the correct filename, if not the correct line number. I'll submit a PR with these changes, but they don't go far enough. Someone will have to invest more time in fixing CppNet itself. Unfortunately it isn't enough of a problem for me, so I'm unlikely to look into this again soon.

Note that I'm specifically talking about **Problem 3**, about line numbers in errors. I *will* work on a fix for **Problem 1**, because that really needs to be fixed before the next MG release.

**Comment by tomspilman** [comment]
> I've been looking at Problem 3. 
> Unfortunately it isn't enough of a problem for me, so I'm unlikely to look into this again soon.

That really can't stand...  I guess I will have to find time to fix CppNet.  We cannot continue with bad line numbers on shader errors.


> I will work on a fix for Problem 1

Isn't that one simple...  just add a newline at the end of the file?

**Comment by tgjones** [comment]
> Isn't that one simple... just add a newline at the end of the file

Basically, yes. At the end of every included file. I have a PR mostly ready.

**Comment by tgjones** [comment]
> That really can't stand... I guess I will have to find time to fix CppNet. We cannot continue with bad line numbers on shader errors.

Have a look at [jcpp](https://github.com/shevek/jcpp), which CppNet was ported from. They've fixed a number of bugs, including line number-related bugs, since CppNet was originally ported.

**Comment by tgjones** [comment]
I've submitted a fix for Problem 1. In @mgarstenauer's original example, the preprocessor still fails, although (for me, anyway) not with the error that @mgarstenauer reported. It now crashes with a NullReferenceException in CppNet. Adding a newline after the `#include` directive fixes it.

So CppNet currently requires that there's a newline after an #include directive - this is a separate issue from the one my PR (#3999) fixes, which is when included files don't end with a newline. Sadly, the more I look at CppNet the more bugs I find...

(I've actually written a mostly complete HLSL preprocessor for my in-progress "HLSL Tools for Visual Studio" VS extension, but that implementation is more aimed at providing intellisense and quick info within the VS editor, rather than actually producing preprocessed code (even though it basically needs to do full preprocessing in order to understand the code), so I'm not suggesting it as an alternative.)

**Comment by tomspilman** [comment]
> So CppNet currently requires that there's a newline after an #include directive

You mean an empty line?  Can you show an example of that error?


> Sadly, the more I look at CppNet the more bugs I find...

Well we've committed to it at this point... we need to fix everything we can.

**Comment by tgjones** [comment]
> Can you show an example of that error?

If the file ends immediately after an `#include` directive, without a newline, CppNet throws a `NullReferenceException`:

```
#include "Example.fxh"
```

But adding a newline after the `#include` directive makes it work:

```
#include "Example.fxh"

```

**Comment by tomspilman** [comment]
> If the file ends immediately after an  #include  directive, without a newline, CppNet throws a  NullReferenceException

So we just need to add a newline to the end of all files... not just included ones.  That should work around that issue.

**Comment by tomspilman** [comment]
@tgjones - Any chance of you taking a second look at problem 3:

> Problem 3: When compiling complex effects with many include files, the line numbers at which errrors are reported are off.

**Comment by tomspilman** [comment]
Going to close this and move further discussion on the error/warning line numbers to https://github.com/mono/MonoGame/issues/4437.
