### ISSUE TITLE
PipelineTool fails to locate MGCB.exe when launced via 'open with'.

### ISSUE THREAD

**Issue by jamesford42** [mono/MonoGame#3926]
I believe there is a difference in the working directory when launching the pipelinetool from visual studio (or double clicking the executable itself) and when it is launched to 'open' a .mgcb file extension. In the second situation, it will correctly open the project but it will fail to locate mgcb.exe when you try to build.

**Comment by tomspilman** [comment]
I don't see how it is possible.

https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L28

That code there defines the paths the Pipeline tool searches for MGCB.exe.  It includes both the current working directory and the directory where the Pipeline.exe exists.  Since the Pipeline Tool and MGCB is installed to the same folder:

https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L84

It should be found in a normal install.

You should check to see where your Pipeline.exe is installed and make sure MGCB.exe is in the same folder.  You should also put a debug build of Pipeline.exe in that folder then debug and see why the path search is failing if it is.

**Comment by jamesford42** [comment]
If you associate PipelineTool.exe with the extension .mgcb, then double click one, the working directory  will be set to WIndows/System32. Thats just the way it works. Hence we cannot rely on the working directory being the location of the executable when resolving relative paths.

**Comment by jamesford42** [comment]
The location where mgcb actual is, is...
``Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),"../../../../../MGCB/bin/Windows/AnyCPU/Debug")``
And that is never checked.

**Comment by tomspilman** [comment]
> And that is never checked.

I see what is happening now.

You associated the development build of the Pipeline tool from your Git source folder with VS.  We never considered that situation.

Make these changes to the search paths:

https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineController.cs#L28

```
        private static readonly string [] _mgcbSearchPaths = new []       
        {
            "",
#if DEBUG
            "../../../../../MGCB/bin/Windows/AnyCPU/Debug",
           Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location, "../../../../../MGCB/bin/Windows/AnyCPU/Debug"),
#else
            "../../../../../MGCB/bin/Windows/AnyCPU/Release",
           Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location, "../../../../../MGCB/bin/Windows/AnyCPU/Release"),
#endif
            "../MGCB",
           Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location, "../MGCB"),
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),
        };
```
It will now check these alternate locations too.

**Comment by jamesford42** [comment]
I had a slightly different solution. #3927

**Comment by tomspilman** [comment]
My concern with your solution is that it will break other cases.  You should not skip the CWD.

**Comment by KonajuGames** [comment]
I added a /workingDir option to mgcb in my etc1 branch because MonoDevelop
doesn't have the option to set a working directory for debugging.​  This
option sets the current directory when processed.
