### ISSUE TITLE
ReadRawAsset for SpriteFont needs to be implemented

### ISSUE THREAD

**Issue by Geertien** [mono/MonoGame#3936]
I hope my conclusion of what the issue should be is correct, but to be sure I will elaborate more.
As I was searching how to draw strings I found a lot of old methods that have been replaced by the new MonoGame Content Pipeline now. To create a .spritefont file with the Pipeline is pretty straightforward and gives no problems, but then it needs to be loaded.
Using content.Load<SpriteFont> throws a NotImplementedException because this leads to a call to ReadRasAsset, which throws that exception when the Type is SpriteFont (with a contruction of a SpriteFont in comment).
If I am correct this means that there is no way to load SpriteFonts at the moment and as you need a SpriteFont to draw a string it is also impossible to draw text at the moment. Thus it is important that this is implemented soon.

Looking at the created .spritefont file however I wonder if the SpriteFont class is meant to be abolished.  I thought this because it states <Asset Type="Graphics:FontDescription">, leading me to think that the type is to be changed to FontDescription. This type does not exist yet however. I was not able to find anything about this possible change however.

Finally I'm sorry if I just misunderstood the way drawing strings must be done now and I simply addressed problems that are not there. I would like to hear so if this is the case however.

**Comment by KonajuGames** [comment]
The content pipeline reads the .spritefont file and generates a .xnb file.  The .xnb file is included in the project's content directory.  The ContentManager.Load() call is falling through to the ReadRawAsset call because you either
- included the .spritefont file in your project instead of the generated .xnb file
- are running the game on a non-Windows platform and got the upper/lower-case of the filename incorrect in the call to ContentManager.Load.

ReadRawAsset will be removed from ContentManager very soon as the content pipeline is more complete and raw assets should be loaded through the LoadFromStream methods of the types that support raw assets (which SpriteFont is not).

**Comment by Geertien** [comment]
Ah ok, as I also made the .spritefont using the pipeline I was confused about this and indeed used the .spriteform instead of the generated .xnb file. Changing this indeed solves the problem.

I still think the NotImplementedException is confusing here, but as the whole method is to be removed this is not really a problem I think.

Thank you for your timely reaction and my apologies for adding this as an issue.

**Comment by KonajuGames** [comment]
No worries.  Closing this issue.
