### ISSUE TITLE
Please update 3.4 installer and packages to include the PCL version

### ISSUE THREAD

**Issue by dsaf** [mono/MonoGame#3944]
The current version of the package is quite old and still beta:

https://www.nuget.org/packages/MonoGame.Framework.Portable/3.2.99.1-Beta

I currently have a well-structured and factored solution with 10 XNA library projects and 10 XNA Windows Phone link projects. I was hoping to just have 10 MonoGame projects after converting to MonoGame, not add another 10 for Android and yet another 10 for iPhone :(. Updating all those links is painful enough for two projects - believe me.

I also have a small physics engine project which only needs Vector2/Quaternion and it would be great to be able to release 1 PCL DLL instead of ~8 for all the platforms.

**Comment by dsaf** [comment]
I am not the only one:

http://community.monogame.net/t/pcl-portable-library-for-monogame-3-4/2607

http://community.monogame.net/t/are-there-monogame-pcl-libraries-for-monogame-3-3/2131

http://community.monogame.net/t/is-it-not-possible-to-share-monogame-code-cross-platform/2400/12

http://community.monogame.net/t/which-physics-engine-is-working-with-monogame/472/58

http://community.monogame.net/t/how-can-i-install-the-portable-version-of-monogame/506

**Comment by tomspilman** [comment]
We are not going to update 3.4.  We will just see about including this in the next release, but it depends on when it is ready to go.

**Comment by dsaf** [comment]
@tomspilman Cool.

Off-topic question: would Patreon work for MonoGame?

Info: https://en.wikipedia.org/wiki/Patreon

Sample: https://www.patreon.com/cmuratori

**Comment by tomspilman** [comment]
We've discussed Patreon before.

We just need to figure out reward levels that would be interesting to people and decide on how we would use the funds coming in.  It can't just go into our pockets as lots of people help and contribute to the project.

**Comment by craftworkgames** [comment]
It's my understanding that the PCL version should be automated with the build so it won't ever get out of date.

@DDReaper mentioned this on #3405 
> Question is now how to provide this framework back in to the MonoGame project so it can be run in an automated fashion.

Has there been any progress on PCL automation for MonoGame 3.5?

**Comment by WardBenjamin** [comment]
I have a simple Piranha implementation based off of @DDReaper's old branch that could be easily adapted for this purpose (as per https://github.com/mono/MonoGame/issues/4056).

**Comment by DDReaper** [comment]
So long as it's tested and offers enough common coverage of the MG framework (i.e. doesn't include iOS/Android only classes), I don't mind who takes it forward :dancer: 
Key thing is to ensure it's automated and the NuGet gets created too with the other DLL's, which is what Prianah was for.

Trouble that @dellis1972 and I ran in to was using the right Piranah command so that the Mono.Cecil output covered enough of the MG API, we found some classes were getting omitted for some reason with some commands.

If you have a working project @WardBenjamin , I suggest also testing it with the MonoGame.Samples projects, to ensure there is enough coverage.

**Comment by WardBenjamin** [comment]
Yeah I can definitely go ahead and try that out today. I'll clone it down and set up basic PCL and Linux projects

**Comment by WardBenjamin** [comment]
@DDReaper Sorry, I've been really busy recently. Either sometime tonight or tomorrow morning I'm going to play with the MonoGame.Samples repo and this new PCL dll (which seems to work fine for MonoGame.Extended).

> Great work picking up the mantle, I got dragged several ways to sunday with work and other projects.

> We are not going to update 3.4.

If this PCL correctly compiles and runs all of the sample projects, could I have access to Nuget as to push up a 3.4 version of this? I can also update it to 3.5 once we finalize a version for that, it'll just be a little late if I'm not informed beforehand.

**Comment by LoveDuckie** [comment]
Hey @WardBenjamin 

Can you get me up to date with what efforts you've made so far to getting the PCL branch working? I've currently got some spare time between projects right now and this is something that I really want to happen.

Right now my plan of attack is to make use of LibCheck (http://www.microsoft.com/en-us/download/details.aspx?id=11287) to compare versions of MonoGame.Framework between themselves. WindowsGL and WindowsDX for example.

From what I have been informed, there are a lot of duplicated user reference/value types dotted around the MonoGame Framework between platform versions. My aim is to reduce as many of them as possible and then generate a PCL branch once I have done some cleaning up.

**Comment by iaingalloway** [comment]
Is there any way I can help to make this happen?

**Comment by LoveDuckie** [comment]
@iaingalloway 

Based on what I understand of the situation right now, there are some problems with the current MonoGame code in that there are duplicate user reference/value types that are spread across the various project versions of the framework. My goal is to remove as much of them as possible, and then utilize a tool that @DDReaper has been using for generating skeleton PCLs that would be used for the bait-and-switch compilation technique so that we can use a PCL lib with the development of our games.

The tool that I am talking about is here.
https://github.com/DDReaper/Piranha

The tool that I am using for checking for duplicate user types between various versions of the library (WindowsGL/WindowsDX) can be found here.
http://www.microsoft.com/en-us/download/details.aspx?id=11287

LibCheck seems to be quite old, so I am hoping that it is still usable. I am going to give it a go when I get some time tonight.

That's as far as I have got so far. I would recommend reading the readmes in the repository that I mentioned regarding @DDReaper.

**Comment by WardBenjamin** [comment]
@LoveDuckie Hey,

I currently have a working PCL (build with Piranha), tested against WindowsGL, Mac, and Linux versions of library. The only issue that I can find is that the version number is off... I don't quite know why that is but that will have to be fixed at some point. All of my code should be in [my PCL_v3.4 branch](https://github.com/WardBenjamin/MonoGame/tree/PCL_v3.4), including a copy of Piranha that I've updated from @Ark-kun's (the original author).

I haven't tested it out, but if you want to run LibCheck against it go ahead.

The build process for the PCL:
 1. Protobuild generate the Windows projects
 2. Build the WindowsGL project and dependencies (MSBuild or whatever you want to use. VS works since it uses MSBuild)
 3. Run [GenerateMonoGamePCL.cmd](https://github.com/WardBenjamin/MonoGame/blob/PCL_v3.4/ThirdParty/Piranha/GenerateMonoGamePCL.cmd) or [GenerateMonoGamePCL.sh](https://github.com/WardBenjamin/MonoGame/blob/PCL_v3.4/ThirdParty/Piranha/GenerateMonoGamePCL.sh), depending on your platform.

**Comment by DDReaper** [comment]
@WardBenjamin The samples repo is the same as any other GitHub project.
Once you have a working PCL sample (no need to update the others until the PCL autogen is up and running), then submit that as a PR to the develop branch of the samples repo

**Comment by LoveDuckie** [comment]
Hi @WardBenjamin,

I just want to double check that you got your copy of Pirahna from the @Ark-kun's original repository, rather than some fork. @DDReaper mentioned to me a while back that he performed some updates in his fork that fixed a few issues with Pirahna. You're confusing me with "updating", given that the origin master has not been updated since January.

Nice work though, I am going to take a look at that now. I'm still looking at using LibCheck for diffing against public types available across all the platform specific versions of MonoGame. I've updated the original source for LibCheck so it no longer uses deprecated types, and so that it uses .NET Framework 4.5.

I recognize that this might not be of interest to you specifically, but I am writing it here for note-storing purposes for other people to see.

Good stuff -- I hope that all of this ends up in the main repository soon enough.

**Comment by LoveDuckie** [comment]
https://github.com/arcanedreams/MonoGame/tree/develop/Tools/LibCheck

**Comment by WardBenjamin** [comment]
Hey @LoveDuckie,

> I just want to double check that you got your copy of Pirahna from the @Ark-kun's original repository, rather than some fork. @DDReaper mentioned to me a while back that he performed some updates in his fork that fixed a few issues with Pirahna.

I did source my copy of Piranha from @Ark-kun's original repo, instead of @DDReaper's fork. It seemed to work fine, and I and the others working on @craftworkgames's  [Monogame.Extended library](http://github.com/craftworkgames/Monogame.Extended) have had no issues building against the PCL binary that I've produced. 

Just so you are aware, I've been really busy getting ready for school to start, but there's an open issue https://github.com/craftworkgames/MonoGame.Extended/issues/36 for me to write down the exact steps and sources that I used to generate the PCL, and there's a copy of the binary itself at https://github.com/craftworkgames/MonoGame.Extended/blob/master/Dependencies/MonoGame.Framework.dll.

> Nice work though, I am going to take a look at that now. I'm still looking at using LibCheck for diffing against public types available across all the platform specific versions of MonoGame.

Another thing that is on the plate for me to do is work with the samples repository and verify that the PCL covers all of the MonoGame API. I think that LibCheck is definitely a good indication of this as well, but I'd still like to run the PCL against the samples.

**Comment by DDReaper** [comment]
Definitely use @Ark-kun's base repo if you can rather than my experimental fork.  I simply replaced the NuGet link to Mono.Cecil to the source version as it appeared I would need to apply changes in the cecil interpreter.  I'd rather avoid those if I can and just use the base project. (@Ark-kun already merged @dellis1972 's mac fixes, so theres no other reason not to use it now)

**Comment by LoveDuckie** [comment]
Should anyone be interested, I made a basic .bat file that is used for cleaning & generating projects, building MonoGame, LibCheck and Piranha through MSBuild and lastly generating the portable libraries with Piranha.

[Link for that on my fork is right here](https://github.com/arcanedreams/MonoGame/blob/develop/Scripts/GenerateAndBuild.bat)

**Comment by DDReaper** [comment]
Several plans have been made but keep getting delayed by other things happening.
The last plan was to get the Core split done first to reduce the bait and switch dependency (since a lot of the requirements for the PCL came from Frameworks just needing a subset of MG, which could be hosted in a true PCL)
Once it's ready, a fully automated PCL build can be generated and added to the project fully.  Key thing is automation so there is no handling involved, a key attribute for it becoming formal

**Comment by Ark-kun** [comment]
>@DDReaper :
>Trouble that @dellis1972 and I ran in to was using the right Piranha command so that the Mono.Cecil output covered enough of the MG API, we found some classes were getting omitted for some reason with some commands.

I guess, you're talking about the *remove-external-types-usage* command.
There are many surprising ways a class can be tangled to some external type.
If you still have any repros, i'd like a bug report. I see a need to update the last commit date =)

BTW, you can look at the trace by redirecting it to console. (See http://stackoverflow.com/questions/198322/redirect-trace-output-to-console)

**Comment by tomspilman** [comment]
I'm replacing this issue with https://github.com/mono/MonoGame/issues/4689.
