### ISSUE TITLE
Missing OcclusionQuery class from Graphics namespace

### ISSUE THREAD

**Issue by CartBlanche** [mono/MonoGame#414]
Someone on twitter who tried to port his app to MonoGame pointed out that we don't have the OcclusionQuery class implemented....

http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.occlusionquery.aspx

Some quick Googling last night shows the OpenGL also has that ability as well and the OpenTK site mentions it here

http://www.opentk.com/doc/chapter/2/opengl/fragment-ops/occlusion-query

Now it seems OcclusionQuery it only valid for the Desktop stack as it is part of OpenGL, but NOT OpenGL ES.

Any suggestions on how we can get it working across all our platforms? Or is it just not worth it due to over heads involved if it is not supported by the mobile hardware?

**Comment by tomspilman** [comment]
We still need someone to implement this for GL platforms... at least for desktops.

Let's also require we add some unit tests for this as well.

**Comment by Jjagg** [comment]
@tomspilman This was already implemented for OpenGL, which is why it isn't in the title of Helikins PR I suppose. He added tests in that PR as well :) 

This is not supported in GLES 2.0, but there is an [extension] we could possibly check. If we'd check for that and add a bool to GraphicsDeviceCapabilities if it's not available, we could add this to iOS and Android too.

**Comment by tomspilman** [comment]
Thanks for letting us know @Jjagg .  This can be closed now I think.
