### ISSUE TITLE
Win Pipeline Tool wrong platform selection

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4154]
So enmus WindowsGL and Linux point to enum DesktopGL, but the problem is that Windows PropertyGrid read the enum Linux first, and since it had the same value as the other 2 it decided to just give "Linux" 3 times in target platform selection instead of giving "WindowsGL", "Linux" and "Mac".

![untitled3](https://cloud.githubusercontent.com/assets/6773302/10102661/fee2f5de-639f-11e5-87a6-f05e934dacb3.png)

**Comment by cra0zy** [comment]
@dellis1972 @KonajuGames Can you add this to 3.5 milestone?

**Comment by cra0zy** [comment]
@nkast Do you by any chance have an idea on how we can fix this?

**Comment by nkast** [comment]
What's the story behind this? Do we keep WindowsGL & Linux for desirialization or something?

Do we want to hide the old values or to keep show them? I tried some attributes (Displayname, editorbrowsable,etc) but nothing works. This probably need a Typeconverter.

**Comment by nkast** [comment]
Wouldn't be better to remove the duplicate values and handle deserialization of older files or that would be extra work? Is this enum used on anything other than .mgcb files;

**Comment by cra0zy** [comment]
> Do we want to hide the old values or to keep show them?

It doesn't matter if WindowsGL/Linux are visible there, the only thing that matters is that DesktopGL is visible.

> Wouldn't be better to remove the duplicate values and handle deserialization of older files or that would be extra work? Is this enum used on anything other than .mgcb files;

They are just used for .mgcb from what I could tell. Also I am fine with what you have suggested.

PS. The best part about this bug is that it doesn't occur on Linux/Mono Windows Forms...

**Comment by nkast** [comment]
The problem is with `SortedEnumTypeConverter` 
https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/Tools/Pipeline/Windows/PipelineProjectProxy.cs#L57

Apart from that, I think we should drop obsolete values from `TargetPlatform and add a `TargetPlatformTypeConverter` to deserialize older files.

**Comment by nkast** [comment]
I made the two obsolete platforms hidden and moved DesktopGL last. 

Everybody seems to agree that `Enum.GetName()` always return the last Field name but officially the documentation says that we shouldn't expect consisted results. Officially this is unfixable!
It makes sense since they all have the same value, it's impossible to determine which is which at runtime.

I suggest to leave this open or open another issue as a reminder that we should clean up TargetPlatform from the obsolete platforms.

**Comment by nkast** [comment]
A better fix (#4350)

**Comment by cra0zy** [comment]
Fixed by @nkast so closing.
