### ISSUE TITLE
SoundEffect is playing garbage instead of WAV loaded via FromStream

### ISSUE THREAD

**Issue by SirCmpwn** [mono/MonoGame#4167]
I'm playing several SoundEffects through SoundEffect.Play. They all come out sounding like:

* Garbage
* The same garbage regardless of what sound is actually played
* The same duration regardless of the duration of the actual sound

I'm loading the sounds with `SoundEffect.FromStream(<wav stream>)`. Here's one of the wavs that demonstrates the issue:

https://sr.ht/18MH.wav

**Comment by StunGunStudios** [comment]
I'm able to play a .wav with no issues like this:

FileStream wav = new FileStream("effect1.wav", FileMode.Open);
sound = SoundEffect.FromStream(wav);

And later calling
sound.Play();

Though normally I just load .xnbs. Is the way you're trying to load it the same way as I described above?

**Comment by SirCmpwn** [comment]
using (var f = File.OpenRead(Path.Combine("Content", "Audio", filenames[i])))
        effects[i] = SoundEffect.FromStream(f);

Have you tried the wav file I provided? I'm on Linux, by the way.

**Comment by StunGunStudios** [comment]
Yes, the .wav you provided works. I'm using Windows 8.1, though...

**Comment by SirCmpwn** [comment]
They have different audio backends, so your point is probably moot.

**Comment by SirCmpwn** [comment]
@flibitijibibo you wouldn't happen to know anything about this, would you?

**Comment by flibitijibibo** [comment]
Not really - the OpenALDevice and SoundEffect implementation in FNA's pretty different from the MonoGame AL now:

https://github.com/flibitijibibo/FNA/tree/master/src/Audio

I would check out the alBufferData call to see if it's just bad parameters leading to OpenAL misinterpreting the bytes being sent.

**Comment by SirCmpwn** [comment]
I spent some time getting TrueCraft to run on top of FNA. I get the same results as I get on MonoGame.

**Comment by flibitijibibo** [comment]
Are you using 24-bit wav files?

**Comment by SirCmpwn** [comment]
The audio file is linked in the OP: https://sr.ht/18MH.wav

And yes.

**Comment by flibitijibibo** [comment]
Ah, so that's the problem then: OpenAL only supports 8- and 16-bit wavedata. 24-bit integer's not supported, even in extension form...

http://repo.or.cz/w/openal-soft.git/blob/HEAD:/include/AL/alext.h

... though if you're looking for higher precision than 16-bit integer, you could see if 32-bit float is any better with AL_EXT_float32, which is something we have support for in FNA internally for DynamicSoundEffectInstance (you could possibly add support to SoundEffect's INTERNAL_loadAudioStream?).

**Comment by SirCmpwn** [comment]
Oh, I see. It'd be great if that were documented somewhere :wink:

I tried converting the wav files to 16 bit and it fixed the issue. Thanks!

**Comment by flibitijibibo** [comment]
For MonoGame it might actually vary somewhat - I _think_ XAudio2 has 24-bit PCM support, but I've not had to deal with porting it... XNA does have a limitation of 16-bit though:

https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.audio.soundeffect.fromstream.aspx

Since FNA just assumes XNA-compatible content you end up with static... I ran into this with Gnomoria too.

**Comment by SirCmpwn** [comment]
Got it, thanks. Side note, how feasible do you think it would be to use FNA's OGG decoder independent of the rest of FNA?

**Comment by flibitijibibo** [comment]
Renaud spent about an hour ganking it from Song to replace his old OggStream in FEZ-FNA, so it should be pretty quick to rip out the FNA-internal bits from it.

**Comment by SirCmpwn** [comment]
Thanks for the info.
