### ISSUE TITLE
"DisplayMode.RefreshRate" can be incorrect (Windows DirectX)

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4221]
I've come across a couple of weird refresh rates such as 59.94006Hz and 59.96894Hz. In the Windows monitor settings, they appear as 59Hz (i.e. truncated). But in MonoGame, they're being rounded to 60Hz.

Normally I guess this wouldn't be much of an issue. But on one of my PCs I have both 59Hz and 60Hz modes, so in MonoGame they are both appearing as 60Hz and look like duplicates.

So the refresh rate needs to at least be truncated to match Windows. However, given that `DisplayMode.RefreshRate` seems to be a MonoGame only property (I couldn't find it in XNA), is there any reason why we can't just make it a float so that the precise refresh rate can be retrieved?

PS. I'm more than happy to submit a PR for this. But I just wanted to confirm how this should be resolved first.

**Comment by tomspilman** [comment]
> However, given that  DisplayMode.RefreshRate  seems to be a MonoGame only property 

Odd... I have no clue why we have that then.  Could it be that XNA 3.x had refresh rates and it was removed in XNA 4?

**Comment by MichaelDePiazzi** [comment]
Ahhh... that might be the case. I can't seem to find it in 4, but it does seem to exist in 3.1 at least - https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.displaymode.refreshrate%28v=xnagamestudio.31%29.aspx

So how should this be handled? Do we need to worry about XNA3 compatibility?

Personally, I'd prefer to have access to the precise refresh rate if possible (may come in handy for sensitive timing related stuff). And give the user the choice on what to do with the value (e.g. use as is, or truncate).

If compatibility needs to be maintained, we could also keep `RefreshRate` as an int, but add a new float (or double) property named `ExactRefreshRate`.

But not really a huge deal to have this as a float I guess.

**Comment by tomspilman** [comment]
Not sure @KonajuGames ?

**Comment by MichaelDePiazzi** [comment]
FYI - Found a post by Shawn Hargreaves explaining why refresh rate was removed from XNA 4:
http://xboxforums.create.msdn.com/forums/p/70732/432151.aspx#432151

He makes some good points. So maybe another option again would be to match XNA 4 and just remove it? Although this would mean that `GraphicsAdapater.SupportedDisplayModes` would need to remove any duplicates arising from multiple refresh rates for the same resolution. XNA is definitely only returning unique resolutions per colour format.

**Comment by tomspilman** [comment]
> So maybe another option again would be to match XNA 4 and just remove it?

Yeah... I agree that is the best way forward.

**Comment by MichaelDePiazzi** [comment]
> Yeah... I agree that is the best way forward.

Ok, I'll submit a PR which removes `DisplayMode.RefreshRate` then (and ignores duplicate resolutions). I'll probably fix issue #4220 first as that's a smaller impact change. But once that fix has been merged, I'll submit a PR for this issue.

**Comment by mrhelmut** [comment]
Ah! Funny, I've been removing duplicates based on ```DisplayMode.RefreshRate``` all along and never noticed it wasn't in XNA 4 anymore... Good to know I'll be able to clean that up.

**Comment by MichaelDePiazzi** [comment]
I've just submitted the fix for #4220. Once that is merged, I'll then submit a PR for this issue.

**Comment by willmotil** [comment]
Just passing by and noticed this.

Before you pull that make sure knowing the refresh rate is not required by arm processors
i have a warning note about that and i think it may have been left in on purpose i don't remember.

**Comment by MichaelDePiazzi** [comment]
@willmotil I did have a look, but I wasn't able to find any usages of `DisplayMode.RefreshRate` in the MonoGame codebase.

@thefiddler @Shqrdx Can you comment on what willmotil has said?

> Before you pull that make sure this refresh rate variable wasn't left in for a special case with arm processors. I cant test that but i have a note about it. It may have been left in on purpose, i don't remember.
> thefiddler or shqrdx would prolly know.

**Comment by Apostolique** [comment]
Does anyone still have the link from Shawn Hargreaves posted above? It's now a dead link. What was the reasoning for removing RefreshRate?

**Comment by vrgamestudio** [comment]
Yes I'd love to know what the reasoning for removing the RefreshRate was as well since it causes (me at least) no end of problems. In UWP there is no ability to pInvoke into User32.dll to grab even the current RefreshRate so we're running blind with no way to know what the refresh rate of the screen is, so should we be VSyncing to it etc etc etc.

**Comment by nkast** [comment]
If you want to match the refresh rate you have to turn on VSync and disable fixedTimeStep.
`
            IsFixedTimeStep = true;
            graphics.SynchronizeWithVerticalRetrace = false;
`

**Comment by mrhelmut** [comment]
There are a lot of arguments that could be made especially nowadays with variable refresh rate being a thing (e.g. NVIDIA Gsync / AMD Freesync). Long story short: a programmatical value of refresh rate can't be trusted. Even if the system might return a value and you might set a value yourself, in the end, it's the GPU driver who decides what the effective rate will be and might totally override whatever value you, or the system, have set.

Most modern approaches in frame pacing involve to just "let go", and implement "frame snapping" / "faked framerate". [Here's a good write up about the subject](https://medium.com/@tglaiel/how-to-make-your-game-run-at-60fps-24c61210fe75).

**Comment by vrgamestudio** [comment]
Thank you both for the replies.

> There are a lot of arguments that could be made especially nowadays with variable refresh rate being a thing (e.g. NVIDIA Gsync / AMD Freesync). Long story short: a programmatical value of refresh rate can't be trusted. Even if the system might return a value and you might set a value yourself, in the end, it's the GPU driver who decides what the effective rate will be and might totally override whatever value you, or the system, have set.
> 
> Most modern approaches in frame pacing involve to just "let go", and implement "frame snapping" / "faked framerate". [Here's a good write up about the subject](https://medium.com/@tglaiel/how-to-make-your-game-run-at-60fps-24c61210fe75).

Ok so let's have that argument then, at least a discussion.

It was indeed an interesting write up but pretty deep, perhaps more of a personal research project than anything else and I was left wondering how different the approach was to Xna's FixedTimeStep? I suspect it's similar but there is some additional arithmetic going on?

For sure, if you're using a FixedTimeStep then you want it to be a good one, no errant accumulations and as correct as it can be.

If it's different then is there a monogame example that follows the reasoning in that write up and achieves the desired result in the monogame framework? If there isn't then, well, how come?

In the past I myself have tried such schemes to override the default rendering loop of Xna/Monogame by forcing an update/draw and ensure it is 1:1 without VSync and avoid "Game Running Slowly" and so on but that seemed to cause input lag and I felt it wasn't a good enough solution to not having VSync.

What I'd like to be able to do is virtually guarantee the user on PC or console will have the best experience out-the-box and from all I've seen, Vsync (even if it must be set by the system) gives the very best results. Is it really correct to simply turn off Vsync in the code and rely on a FixedTimeStep in the hope that their system is up-to-date and smart enough to G-Sync/A-Sync/Freesync based on the FixedTime approach? For one example I believe Xbox now supports VRR but only if the TV is compatible. That sounds like at least a fragmented market and I don't believe it is right to assume this technology is in place for all users.

Speaking personally I have a 120Hz screen on my laptop with a GTX1060. I think it has Adaptive VSync but I don't think it's enabled and honestly I don't even know how I would do such a thing. All I know is that I can't choose 60Hz from the usual windows menus, it's 120Hz or nothing. 

So although some will care very much on PC, I'm fairly convinced that even most PC gamers don't know or care about whether or not they've enabled Freesync or G-Sync or Adaptive Sync and especially not for a monogame game. The chances are if you've written a game in Monogame it probably isn't the most taxing to their system and the problem won't be so much them running too slow and having to adaptive VSync to avoid stutters, it will be them running too fast with their 120Hz+ monitor and the poor developer just put this in their Game1 constructor because someone told him to:

```
IsFixedTimeStep = false;
graphics.SynchronizeWithVerticalRetrace = true;
```

To get the correct frame pacing you'd want to have VSync, whether their system enables/creates that for you or your game code *at least tries* to set it correctly.

If it means the game must provide options to turn off VSync and allow the user to tinker or let their system take over then so be it but it doesn't help the situation to have no idea whatsoever what even their "system says" their screen refresh is, to at least set a good faith default. Yes in theory the default *might* be wrong but for the majority probably wouldn't be and at the very least, you tried and you can provide options to disable VSync in favour of a FixedTimeStep (or modified version thereof).

Unity on the other hand seems to have this about right. You can read at least what the *system thinks* the Screen Refresh rate is, even on UWP. You can set the desired framerate (ala FixedTimeStep) as an Integer with -1 being "default for system", and you can Vsync to 0, 1, 2, 3 or 4 (0 being no Vsync). When VSync > 0 then the "FixedTimeStep" does not apply. 

For example if you have a game that you want to run at 60FPS and the user *seems to have* a 75Hz screen then great, detect that 75Hz, default to disable VSync and "let it go" using your desired 60FPS framerate to dictate the timing to Freesync or G-Sync etc. On the other hand if they *appear to have* a 60Hz screen and you want 60FPS then again set your desired 60 framerate but a nice default would be VSync = 1 and the job is more than likely done. In all cases give them the tools to alter your defaults if they desire.

I'd love there to be a simple, bulletproof solution to be used in Monogame projects.
