### ISSUE TITLE
Some API for remapping Gamepad

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4322]
XNA never needed it since it only used Microsoft controllers, but it would make sense to setup a way for easy remapping of buttons/axes/dpad for Gamepad class.

@tomspilman @KonajuGames @dellis1972 What do you think?

**Comment by tomspilman** [comment]
IMO that is really something for your own engine or game code.

**Comment by cra0zy** [comment]
Since I didn't really explain what I meant, I am talking about something like: https://github.com/opentk/opentk/blob/develop/Source/OpenTK/Input/GamePadConfigurationDatabase.cs#L81, just making some way to load GamePad config that isn't platform specific.

**Comment by tomspilman** [comment]
> just making some way to load GamePad config that isn't platform specific.

I think i see.  

This isn't a feature for remapping buttons on your Xbox gamepad because you like Jump on X and not Y or something.

This if for defining button mappings for uncommon controllers that otherwise would get some weird default mapping that make no sense.

While it can be abused to do gameplay remapping...  it still isn't meant for that.

**Comment by cra0zy** [comment]
With SDL branch now there is a way to load custom configs, therefore closing...
