### ISSUE TITLE
Possible bug in PixelBitmapContent.cs

### ISSUE THREAD

**Issue by Tzenchor** [mono/MonoGame#4560]
I have been working on the renderer for font styles and was trying to reuse the current instance of `BitmapContent`. The problem arised when I tried to resize the bitmap, I began getting exceptions when calling `BitmapContent.SetPixelData(byte[])` because after setting the new size, the data array still has the old size.
First I thought that he properties `Width` and `Height` should be read only, but looking into the XNA documentation both of them are read and write properties.
Then I looked into the property implementation, and it does nothing apart from changing the corresponding field.
And last I saw the data container that is defined in this case in `PixelBitmapContent`, it is a jagged array with an array for the rows that contains more arrays for the data of each row. This makes enlarging the width or the height make the data wrong, and method `GetPixelData` and `SetPixelData` prone to memory corruption.

Also looking at other siblings of `PixelBitmapContent` like `DxtBitmapContent` or `Etc1BitmapContent` use a simple byte array for the data.

**Comment by KonajuGames** [comment]
Resizing a PixelBitmapContent in place is not something the content
pipeline does, so it has never been tested. It creates a new instance of
the desired size, followed by a copy of the original contents are to be
kept.

It uses a jagged array internally in order to support the GetRow() method.
The other bitmap types don't support GetRow(), so they just use a single
dimension array.

In fixing this, I'm assuming XNA does not keep the original contents if
either the Width or Height properties are modified. Can anyone confirm that?

**Comment by tomspilman** [comment]
@KonajuGames - Sounds like a job for more unit tests!

Speaking of I will be getting the XNA unit tests running as part of our build process soon.

**Comment by tgjones** [comment]
I tried to write a test to tease out XNA's behaviour, but quickly found that XNA's `BitmapContent` doesn't have public `Width` and `Height` setters, despite what it says on MSDN. So I've submitted a PR to fix this in MonoGame.

**Comment by KonajuGames** [comment]
I like that fix better. A bitmap object should be created at the desired size and it stays that size for its lifetime, which as you found is how XNA works.
