### ISSUE TITLE
Eto.Forms and Pipeline.Windows

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#4778]
In the MG Windows solution there is Pipeline.Windows, a project that seems to use Eto.Forms. Yet, I don't see a packages config to restore the Eto.Forms NuGet package. Should this be manually installed or is Pipeline.Windows supposed to use NuGet to bind Eto.Forms?

**Comment by angrywasp** [comment]
I would imagine that if a project depends on a nuget package it should pull it in automatically. To not so that would be a bug IMO.

There should be no problem with manually installing it though. I see you have a fork of your own, so it may be beneficial to manually install it and create a PR with the new files. That will probably be the fastest way to resolve the issue. It is most likely just an oversight to include the packages.config in the repo

**Comment by KonajuGames** [comment]
Eto is in the Dependencies repo, built from modified source. There is an outstanding PR to update Eto in the repo.

**Comment by angrywasp** [comment]
OK. Fair enough. Can you please explain the decision to include it in the dependencies rather than using the official nuget package?

**Comment by KonajuGames** [comment]
Can't use the official Nuget package if you want to modify it (fix bugs, etc).

**Comment by totallyeviljake** [comment]
Thanks Steve, that did it.

**Comment by cra0zy** [comment]
Shouldn't this be closed?
