### ISSUE TITLE
XB1 UWP doesn't like how our static VBs and IBs are created

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4829]
For some reason on XB1 via UWP both `VertexBuffer` and `IndexBuffer` fail to work, but `DynamicVertexBuffer` and `DynamicIndexBuffer` work fine.

What is particularly curious about this is that things work perfectly fine under UWP on Windows 10 desktops and on UWP under Raspberry Pi.  Also the exact same code works on Windows 7, Vista, and Windows 8.  It is just on XB1 where the non-dynamic buffers fail to work.

I suspect it is either something something in buffer setup:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexBuffer.DirectX.cs#L44

Or it is something in the buffer `SetData` which takes a different path for dynamic vs static buffers:
  https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexBuffer.DirectX.cs#L121
  
It could very well be that the code that has worked for 5 years now on every other DX platform has been wrong and the drivers and/or the DX runtime has been letting us get away with it.

**Comment by tomspilman** [comment]
I suspect this issue might just be a buffer creation issue...  in particular not setting `CpuAccessFlags.Write` on static buffers.  Now the official DirectX docs have examples which set the CPU access flag to zero like we do:

https://msdn.microsoft.com/en-us/library/windows/desktop/ff476899(v=vs.85).aspx

But I suspect that maybe XB1  might be more strict about memory access restrictions.

@BrianPeek - Any ideas?

**Comment by KonajuGames** [comment]
It would make sense that `CpuAccessFlags.Write` would be required so that `SetData()` can do its job.

**Comment by tomspilman** [comment]
> It would make sense that  CpuAccessFlags.Write  would be required so that  SetData()  can do its job.

I agree...  but if so it was never enforced on any other DX platform.

Just need someone with XB1 UWP setup to give it a test and be sure it doesn't adversely affect any other DX platforms (like if it affects performance).

**Comment by walbourn** [comment]
I just tried a simple setup with Windows 10 (10586) in a UWP and I get a Direct3D 11validation failure if I attempt to create a dynamic VB resource without ``D3D11_CPU_ACCESS_WRITE``.

    D3D11 ERROR: ID3D11Device::CreateBuffer: A D3D11_USAGE_DYNAMIC Resource may have only the D3D11_CPU_ACCESS_WRITE CPUAccessFlags set.
    [ STATE_CREATION ERROR #63: CREATEBUFFER_INVALIDCPUACCESSFLAGS]

**Comment by tomspilman** [comment]
First... thanks for checking this out @walbourn !

>  I get a Direct3D11 validation failure if I attempt to create a dynamic VB resource without  `D3D11_CPU_ACCESS_WRITE`.

Right...  we're definitely not trying to do that.

Our case is that `D3D11_USAGE_DEFAULT` buffers do not work on XB1 UWP, but work fine on all other DX platforms.

If I remember correctly from last time I debugged it... the creation of the buffer succeeded, but copying data into the buffer didn't.

> you will update this resource via `CopyResource` likely from a `D3D11_USAGE_STAGING` resource or via `UpdateSubresource`.

Right...  in the `D3D11_USAGE_DEFAULT` case we are using `UpdateSubresource` and `CopyResource` depending on if we're replacing all the data or doing a partial update.

> DirectX Tool Kit works fine on Xbox One UWP, but all the 'static buffers' in the library use `initData`.

Right... we've discussed before extending MonoGame to support a constructor for buffers that takes initial data.  It should be something to consider once we break with XNA4 standards.


> one thing I note is that your code is creating a `stagingBuffer` on the fly

Right... we should clean that up to be pooled...  however it doesn't occur frequently as it only uses the staging buffers when doing a partial update of a static buffer.

Anyway...  in my test case the problem occurred with `UpdateSubresource`.

I'll try to fire it up in the next day or so and dig deeper into it.

> The other issue is that Xbox One UWP is very memory constrained--the bulk of the RAM and VRAM is dedicated for game use. Is it possible you are hitting these limits?

I doubt it...  the test case I had was really simple.

> what memory model is being used here? Is it `/platform:x86`,  `/platform:x64` or something else?

The sample i was running was x64 on XB1.

**Comment by walbourn** [comment]
You might also to try it with ``ID3D11DeviceContext1::UpdateSubresource1`` rather than the older ``ID3D11DeviceContext::UpdateSubresource``

**Comment by stonstad** [comment]
I'm following along with this thread and I created a simple test case to test dynamic and static vertex buffers.  Perhaps it might help someone following this thread.    

Simple Test Case:
https://www.youtube.com/watch?v=3DpNvF9Ogp8
https://stellarconquest.blob.core.windows.net//Test.zip

If I comment out Line 155 in VetexBuffer.DirectX.cs in PlatformSetDataInternal<T>  
... (if (vertexStrid == elementSizeInBytes) 

to force the alternate code path the static vertex buffer works.  

I imagine this isn't too helpful since the goal is to use UpdateSubresource instead of MapSubresource.  

How would I go about testing UpdateSubresource1?  It looks like this method is not exposed in SharpDX...

**Comment by stonstad** [comment]
@walbourn  SharpDX appears to use a workaround for UpdateSubresource based on your [blog post here](https://blogs.msdn.microsoft.com/chuckw/2010/07/28/known-issue-direct3d-11-updatesubresource-and-deferred-contexts/).  Looks like a straight up copy of the proposed workaround.  I am still unsure of what could cause this behavior on XB1.

**Comment by stonstad** [comment]
I really want to help out but I am spinning my wheels.  I downloaded source for SharpDX and compiled a debug build so that I could see DirectX debug output.  I see debug output in local development but from XB1 I am not seeing any messages after this trace appears:

`Xbox User Mode Driver for Direct3D 11.1 / App`

I am thinking I need to find a way to turn on debug output programmatically in SharpDX.

I tried UpdateResourceSafe which uses @walbourn approach in his blog.  I forced needsWorkaround to true to see if this would affect a change.  I also tried other UpdateSubresource method overloads without success.  My static vertex buffer triangle renders on x86/x64 locally but won't display on XB1.

I tried adding UpdateSubresource1 to the SharpDX mapping file prior to generation but it thwarted me.  I have mostly failed.  

One thing that I wanted to ask -- what is the advantage of using UpdateSubresource  compared to deviceContext->IASetVertexBuffers?  I am not suggesting we should do this -- I have rudimentary knowledge of native DirectX.  I am just curious and desire to understand the code more.

**Comment by tomspilman** [comment]
@walbourn - Found the bug https://github.com/mono/MonoGame/pull/4955.  Turned out to be a simple issue, but one that didn't manifest on any other platform but UWP-XB1.

@stonstad - Can you give my fix a test?

**Comment by stonstad** [comment]
Sure thing -- I'll test it out tonight and report back.

**Comment by stonstad** [comment]
Tested with Windows 10 14366 SDK w/ June 2016 XB1 SDK.  Success!

**Comment by tomspilman** [comment]
Great... thanks for testing it @stonstad !

**Comment by shuawinn** [comment]
Is there a way to pull this fix down? I'm running Monogame 3.5 and am having the same issue when trying to deploy to my xbox one.

**Comment by tomspilman** [comment]
@shuawinn - you can try to git cherrypick this one commit...

https://github.com/mono/MonoGame/pull/4955/commits/ba190e7764ac71833e2336b9e51f0bf9fe7ca065

... or just cut and paste the changes into your own copy of the code.

**Comment by shuawinn** [comment]
I had to pull the entire repo down and build the solution, just got it to work. Thanks for the pointer!
