### ISSUE TITLE
monogame pipeline keybinding for close

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#4839]
Hi,

monogame pipeline (windows) uses Control+C for closing. Is it possible to change it? (i.e. to Control+W which is a more standard windows closing keybinding). Current keybinding makes impossible to copy text from the output.

**Comment by tomspilman** [comment]
Oh yea...  that is horrible.

Actually for Windows `ALT+F4` is the standard for exiting an application.  We should be using that.

**Comment by KakCAT** [comment]
well, control+c is closing the project (not the app). Alt+f4 would be more for closing the app (which should already be closing it as it's a system keybinding). Maybe Ctrl+F4?  (IE and firefox close the tabs with both Ctrl+F4 and Ctrl+W)

**Comment by KonajuGames** [comment]
Ctrl+C is even standard in Linux GUI applications for copying to clipboard,
so it should not be used for closing anything.  On the command-line it
sends a SIGTERM to the applucation.  Ctrl+F4 is usually for closing the
current document in Windows.  If we really need a key shortcut, Ctrl+F4 is
much more acceptable.  The other option is that Close does not need a
keyboard shortcut, because the New, Open and Exit actions that have
keyboard shortcuts already imply a Close anyway, and what use is a Close if
it is not followed immediately by a New, Open or Exit?

**Comment by cra0zy** [comment]
I vote for Ctrl+W for Close. Both Chrome and Opera use it for closing tabs and I got used to it...

> Actually for Windows ALT+F4 is the standard for exiting an application. We should be using that.

Talking about Close Project, not Exit Application.

**Comment by Halofreak1990** [comment]
@cra0zy Is a shortcut really needed for close? I'm with @KonajuGames on not having a shortcut for close.

**Comment by cra0zy** [comment]
> @cra0zy Is a shortcut really needed for close? I'm with @KonajuGames on not having a shortcut for close.

I'm fine with that too.

**Comment by tomspilman** [comment]
> I'm fine with that too

Yeah... we don't need a shortcut for "Project Close".  Let's just remove it.

**Comment by cra0zy** [comment]
Should we change the build key for "Build" as well and should we maybe add keyboard shortcuts for "Rebuild/Clean"?

**Comment by cra0zy** [comment]
Well for now #4844
