### ISSUE TITLE
IntermediateSerializer does not create compatible xml structures.

### ISSUE THREAD

**Issue by JakeClarke** [mono/MonoGame#676]
A common way of generating basic xml files in xna is to use the IntermediateSerializer, which currently does not treat the MonoGame Vector2 type the same as XNA's Vector2 type, this probably extends to other data basic types such as Rectangle, Vector3 etc.

A Vector2 example of the generated and expect input within the content pipe line would be:
Monogame
```xml
        <position>
          <X>200</X>
          <Y>200</Y>
        </position>
```
Non Monogame:
```xml
        <position>200 200</position>
```
Notice the additional X and Y elements.
This is likely unexpected behavior and would probably create confusion when migrating.
Seen within the Develop branch.

**Comment by tgjones** [comment]
I think this can be closed once #3377 is merged?

**Comment by Aranda** [comment]
This is awesome, thanks @tgjones !. We also use Intermediate format XML for saving files from our editor. Having the the Serialize() functionality working means we could keep the same format for user defined content, either saved by the game or we could distribute the editor itself (which was always a problem due to the XNA EULA forbidding distribution of the content pipeline assemblies).

**Comment by tgjones** [comment]
@Aranda Cool :) I'm glad others will make use of it too.
