### ISSUE TITLE
Strange colors in MonoGame on OS X

### ISSUE THREAD

**Issue by turn1p** [mono/MonoGame#985]
I have my game project running in MonoDevelop using MonoGame on OS X, but the colors in the game are very mixed up. For example, yellow is shown as blue. What could be causing this? My game is ported from XNA. The android and iOS ports don't have this color problem.

**Comment by tomspilman** [comment]
This likely can be closed...  @KonajuGames @dellis1972 ?

**Comment by mrhelmut** [comment]
Never seen that on develop branch.

**Comment by turn1p** [comment]
Sorry guys I didn't even realize I hadn't finished posting in this thread. The problem was solved elsewhere, but apparently back in 2012 (lol) I didn't remember to post here what the solution was (which I vaguely remember being something about changing something in that particular version of MonoGame from BGRA to RGBA).

**Comment by anthonyhan** [comment]
had this issue on iPhone 8 plus.
monogame version: 3.7.1 
Using ConvertToABGR( ) fixed this bug.

**Comment by mickbyrne** [comment]
Hi, I'm having this problem on iOS devices. Can you explain a bit more about how "using ConvertToABGR() fixed this bug."? I can't find this method, not sure where to call it?

**Comment by anthonyhan** [comment]
If you are loading a raw png file via `Texture2D.FromStream` on iOS. You'll probably encounter this problem.
The reason is this. the `Texuture2D` type texture on iOS is ABGR format which is different from ARGB format. You have to convert the pixel format from ABGR to ARGB.

You can find the following code [here](https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.cs#L349-#L358)
```csharp
 //Converts Pixel Data from ARGB to ABGR
        private static void ConvertToABGR(int pixelHeight, int pixelWidth, int[] pixels)
        {
            int pixelCount = pixelWidth * pixelHeight;
            for (int i = 0; i < pixelCount; ++i)
            {
                uint pixel = (uint)pixels[i];
                pixels[i] = (int)((pixel & 0xFF00FF00) | ((pixel & 0x00FF0000) >> 16) | ((pixel & 0x000000FF) << 16));
            }
        }
```

Besides that, there's another problem you should notice. After converting ABGR to ARGB, if the image still has strange colors, maybe it's caused by the premultiplied alpha process. If it happend, you can remove the premultiplied alpha. 
```csharp
uint a = (argb & 0xFF000000) >> 24;
if (a != 0)
{
    float ap = 255f / a;
    uint r = (uint)(((argb & 0x00FF0000) >> 16) * ap);
    uint g = (uint)(((argb & 0x0000FF00) >> 8) * ap);
    uint b = (uint)(((argb & 0x000000FF)) * ap);
    argb = (a << 24) | (r << 16) | (g << 8) | (b);
}
```
(Not recommended. If there's no prolem,  using a premultiplied alpha image is a better choice.)
